ABC:
  VERSION: 3.3.0
AB_HISTDB_DETAILS:
  USE_AB_HISTDB: false
BROKING_DETAILS: { }
CANDLE:
  CANDLE_INTERVAL: 60minutes
EXIT:
  EXIT_INTRADAY_ORDERS_ON_STOP: false
  EXIT_TPLUS0_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS1_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS2_DELIVERY_ORDERS_ON_STOP: false
FUNDS:
  CREDIT_EXPOSURE_FACTOR: 100000
  INITIAL_FUNDS_VIRTUAL: 1000000000
MISC:
  CROSSOVER_ACCURACY_DECIMALS: 2
  CUSTOMER_SESSION_TOKEN: null
  MAX_ORDERS_COUNT: 100
RESUME:
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS1: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS2: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_POSITIONS: false
  RESUME_HOLDINGS_TPLUS1_ON_START: true
  RESUME_HOLDINGS_TPLUS2_ON_START: true
  RESUME_POSITIONS_ON_START: true
RISK_MANAGEMENT:
  PNL_SCAN_FREQUENCY: 30
  PROFIT_DESIRED: null
  RISK_APPETITE: null
STRATEGY:
  INSTRUMENTS_BUCKET:
    - NASDAQ:MSFT
  MODE: INTRADAY
  NAME: Options Long Iron Butterfly
  NUMBER_OF_LOTS: 1
  PARAMETERS:
    LEG_FOUR_NUMBER_OF_STRIKES: 2.0
    LEG_FOUR_STRIKE_DIRECTION: 2.0
    LEG_FOUR_TRADING_SYMBOL_SUFFIX: 2.0
    LEG_FOUR_TRANSACTION_TYPE: 2.0
    LEG_ONE_NUMBER_OF_STRIKES: 1.0
    LEG_ONE_STRIKE_DIRECTION: 0.0
    LEG_ONE_TRADING_SYMBOL_SUFFIX: 1.0
    LEG_ONE_TRANSACTION_TYPE: 1.0
    LEG_THREE_NUMBER_OF_STRIKES: 2.0
    LEG_THREE_STRIKE_DIRECTION: 2.0
    LEG_THREE_TRADING_SYMBOL_SUFFIX: 2.0
    LEG_THREE_TRANSACTION_TYPE: 1.0
    LEG_TWO_NUMBER_OF_STRIKES: 2.0
    LEG_TWO_STRIKE_DIRECTION: 0.0
    LEG_TWO_TRADING_SYMBOL_SUFFIX: 1.0
    LEG_TWO_TRANSACTION_TYPE: 2.0
  SECURE: true
SYSTEM:
  FAST_MODE: true
  TRADING_END_TIME: 14-05-2024 16:00 -0400
  TRADING_START_TIME: 14-05-2024 09:30 -0400
  TRADING_TYPE: BACKTESTING
